# Imports

In [ ]:
import numpy as np
from sklearn import neighbors,datasets,metrics


# Loading data set


In [ ]:
X,y = datasets.load_iris(return_X_y=True)
X_train = X[range(0,150,2),:]
y_train = y[range(0,150,2)]

X_test = X[range(1,150,2),:]
y_test = y[range(1,150,2)]



# Neighbors and weight ( parameters )

In [ ]:
n_neighbors = 1

In [ ]:
weights = 'uniform'

# KNN classifier

In [ ]:
clf = neighbors.KNeighborsClassifier(n_neighbors,weights)


C:\Users\aman shaikh\anaconda3\lib\site-packages\sklearn\utils\validation.py:67: FutureWarning: Pass weights=uniform as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


# Training set


In [ ]:
clf.fit(X_train,y_train)
prediction = clf.predict(X_test)

# Prediction

In [ ]:
print("----------------------------------")
print("Predictions")
print(prediction)
print("----------------------------------")

----------------------------------
Predictions
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 1 2 2 2 2 2 2 2
 2]
----------------------------------


# Accuracy

In [ ]:
print("Accuracy= ",metrics.accuracy_score(y_test,prediction))

Accuracy=  0.96


# Classification report

In [ ]:
print(metrics.classification_report(y_test,prediction))
print(metrics.confusion_matrix(y_test,prediction))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       0.92      0.96      0.94        25
           2       0.96      0.92      0.94        25

    accuracy                           0.96        75
   macro avg       0.96      0.96      0.96        75
weighted avg       0.96      0.96      0.96        75

[[25  0  0]
 [ 0 24  1]
 [ 0  2 23]]


# For finding best parameters

In [ ]:
clf = neighbors.KNeighborsClassifier()


In [ ]:
param_grid = [{'n_neighbors':[1,5,7,10,15,20,30,40,50],'weights':['uniform','distance']}]

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
clf_gs = GridSearchCV(clf,param_grid,cv=5)


In [ ]:
clf_gs.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid=[{'n_neighbors': [1, 5, 7, 10, 15, 20, 30, 40, 50],
                          'weights': ['uniform', 'distance']}])

In [ ]:
print(clf_gs.best_params_)

{'n_neighbors': 5, 'weights': 'uniform'}


In [ ]:
prediction=clf_gs.predict(X_test)
print("----------------------------------")
print("predictions")
print(prediction)
print("----------------------------------")

----------------------------------
predictions
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 2 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2]
----------------------------------


In [ ]:
print("Accuracy ",metrics.accuracy_score(y_test,prediction))
print(metrics.classification_report(y_test,prediction))
print(metrics.confusion_matrix(y_test,prediction))

Accuracy  0.9866666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        25
           1       1.00      0.96      0.98        25
           2       0.96      1.00      0.98        25

    accuracy                           0.99        75
   macro avg       0.99      0.99      0.99        75
weighted avg       0.99      0.99      0.99        75

[[25  0  0]
 [ 0 24  1]
 [ 0  0 25]]
