In [ ]:
import pandas as pd
Rid = [*range(1,15,1)]
age = ['Youth','Youth','Middle-Age','Senior','Senior','Senior','Middle-Age','Youth','Youth','Senior','Youth','Middle-Age','Middle-Age','Senior']
income = ['High','High','High','Medium','Low','Low','Low','Medium','Low','Medium','Medium','Medium','High','Medium']
student = ['No','No','No','No','Yes','Yes','Yes','No','Yes','Yes','Yes','No','Yes','No']
credit_rating = ['Fair','Excellent','Fair','Fair','Fair','Excellent','Excellent','Fair','Fair','Fair','Excellent','Excellent','Fair','Excellent']
Buys_computer = ['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

dict = {'RID':Rid,'Age':age,'Income':income,'Student':student,'Credit_Rating':credit_rating,'Class':Buys_computer}
df = pd.DataFrame ( dict )
df.to_csv('Electronic.csv',index=False)

In [ ]:
import pandas as pd
Dataset = pd.read_csv('Electronic.csv')
df=pd.DataFrame(Dataset)
object_df=df.select_dtypes(include='object')
df.loc[:,object_df.columns]=object_df.apply(lambda x : pd.factorize(x)[0])
Dataset=df
df.to_csv('Electronic_catagorical.csv',index=False)

**Gaussian Naive Bayes fot the Electronic Data** **Set** **bold text**

In [ ]:
import numpy
from sklearn import datasets, metrics
from sklearn.naive_bayes import GaussianNB
import pandas as pd
Dataset=pd.read_csv('Electronic_catagorical.csv')

Train_x=Dataset[["RID","Age","Income","Student","Credit_Rating"]]
Train_y=Dataset["Class"]
X_Train=Train_x.head(10)
Y_Train=Train_y.head(10)

Test_x=Dataset[["RID","Age","Income","Student","Credit_Rating"]]
Test_y=Dataset["Class"]
X_Test=Test_x.tail(4)
Y_Test=Test_y.tail(4)

clf=GaussianNB()

clf.fit(X_Train, Y_Train)

prediction = clf.predict(X_Test)

print("----------Predictions------------")
print(prediction)
print("---------------------------------")

print("Accuracy:",metrics.accuracy_score(Y_Test, prediction,normalize=True))
print(metrics.classification_report(Y_Test, prediction))
print(metrics.confusion_matrix(Y_Test, prediction))

----------Predictions------------
[0 0 1 1]
---------------------------------
Accuracy: 0.25
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      0.33      0.40         3

    accuracy                           0.25         4
   macro avg       0.25      0.17      0.20         4
weighted avg       0.38      0.25      0.30         4

[[0 1]
 [2 1]]


**Multinimial Navie Bayes for the Electonic Data Set**

In [ ]:
import numpy
from sklearn import datasets, metrics
from sklearn.naive_bayes import MultinomialNB
import pandas as pd
Dataset=pd.read_csv('Electronic_catagorical.csv')

Train_x=Dataset[["RID","Age","Income","Student","Credit_Rating"]]
Train_y=Dataset["Class"]
X_Train=Train_x.head(10)
Y_Train=Train_y.head(10)

Test_x=Dataset[["RID","Age","Income","Student","Credit_Rating"]]
Test_y=Dataset["Class"]
X_Test=Test_x.tail(4)
Y_Test=Test_y.tail(4)

clf=MultinomialNB()

clf.fit(X_Train, Y_Train)

prediction = clf.predict(X_Test)

print("----------Predictions------------")
print(prediction)
print("---------------------------------")

print("Accuracy:",metrics.accuracy_score(Y_Test, prediction,normalize=True))
print(metrics.classification_report(Y_Test, prediction))
print(metrics.confusion_matrix(Y_Test, prediction))

----------Predictions------------
[0 0 1 1]
---------------------------------
Accuracy: 0.25
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.50      0.33      0.40         3

    accuracy                           0.25         4
   macro avg       0.25      0.17      0.20         4
weighted avg       0.38      0.25      0.30         4

[[0 1]
 [2 1]]


**Bernoulli Naive Bayes For the Electronic Data Set**

In [ ]:
import numpy
from sklearn import datasets, metrics
from sklearn.naive_bayes import BernoulliNB
import pandas as pd
Dataset=pd.read_csv('Electronic_catagorical.csv')

Train_x=Dataset[["RID","Age","Income","Student","Credit_Rating"]]
Train_y=Dataset["Class"]
X_Train=Train_x.head(10)
Y_Train=Train_y.head(10)

Test_x=Dataset[["RID","Age","Income","Student","Credit_Rating"]]
Test_y=Dataset["Class"]
X_Test=Test_x.tail(4)
Y_Test=Test_y.tail(4)

clf=BernoulliNB()

clf.fit(X_Train, Y_Train)

prediction = clf.predict(X_Test)

print("----------Predictions------------")
print(prediction)
print("---------------------------------")

print("Accuracy:",metrics.accuracy_score(Y_Test, prediction,normalize=True))
print(metrics.classification_report(Y_Test, prediction))
print(metrics.confusion_matrix(Y_Test, prediction))

----------Predictions------------
[0 1 1 1]
---------------------------------
Accuracy: 0.5
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.67      0.67      0.67         3

    accuracy                           0.50         4
   macro avg       0.33      0.33      0.33         4
weighted avg       0.50      0.50      0.50         4

[[0 1]
 [1 2]]
